# treknote version

TREKNOTE_MAJOR_VERSION  = 0
TREKNOTE_MIDDLE_VERSION = 1
TREKNOTE_MINORE_VERSION = 1

TREKNOTE_VERSION = "#{TREKNOTE_MAJOR_VERSION}.#{TREKNOTE_MIDDLE_VERSION}.#{TREKNOTE_MINORE_VERSION}"
